name: CI/CD
on:
  push:
    branches:
      - master

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: install deps
        run: npm install

      # - name: deploy
      #   run: npm run deploy
      # - name: deploy with gh pages
      #   run: |
      #     git remote set-url origin https://git:${secrets.CI_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
      #     npx gh-pages -d build -u "github-actions-bot <support+actions@github.com>"
      - name: deploy
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: gh-pages
          build_dir: build
        env:
          GITHUB_TOKEN: ${{ secrets.CI_TOKEN }}
