name: CI/CD
on:
  push:
    branches:
      - master

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: install deps
        run: npm install
      - name: deploy
        run: npm run deploy

      # - name: deploy
      #   uses: crazy-max/ghaction-github-pages@v3
      #   with:
      #     target_branch: gh-pages
      #     build_dir: build
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.CI_TOKEN }}
